setwd('~/Chapter_1-2')
glowworms <- read.csv('~/Chapter_1-2/GlowWorms.csv')
glowworm_reg = lm(Eggs~Lantern, data = glowworms)
summary(glowworm_reg)
with(glowworms,plot(Lantern,Eggs))
plot(glowworm_reg)

predict(glowworm_reg,data.frame(Lantern=14),interval='confidence')


RailsTrails <- read.csv('~/Chapter_1-2/RailsTrails.csv')
with(RailsTrails, plot(squarefeet,adj2007))
railstrails_reg <-lm(adj2007~squarefeet, data = RailsTrails)
summary(railstrails_reg)

volts <- read.csv('~/Chapter_1-2/Volts.csv')

volts_reg = lm(Voltage~Time, data = volts)
with(volts, plot(Time,log(Voltage))
par(mfrow=c(2,2))
plot(volts_reg)
with(volts, plot(Time, logvoltage))

logvolts_reg = lm(logvoltage~Time, data = volts)
logvoltage= log(Voltage)
log(5)
with(volts,log(Voltage))
volts$logvoltage <- with(volts,log(Voltage))
summary(logvolts_reg)
par(mfrow =c(2,2))
plot(logvolts_reg)
baseballtimes <- read.csv('~/Chapter_1-2/BaseballTimes2017.csv')
times <- with(baseballtimes,plot(Time))
timesvpitches = lm(Pitchers~Time, data = baseballtimes)
summary(timesvpitches)
timesvruns = lm(Runs~Time, data = baseballtimes)
summary(timesvruns)
confint(timesvruns)
confint(timesvpitches)
plot(timesvruns)
with(baseballtimes, plot(Time,Runs))
with(baseballtimes, plot(Time,Pitchers))
with(baseballtimes, cor(Time,Pitchers))
with(baseballtimes, cor(Time,Runs))
summary(timesvpitches)
summary(timesvruns)
countyhealth <- read.csv('~/Chapter_1-2/CountyHealth.csv')
countyhealth$logmd <- with(countyhealth, log(MDs))
countyhealth$loghospital <-with(countyhealth, log(Hospitals))
with(countyhealth, plot(Hospitals,MDs))
with(countyhealth, plot(loghospital,logmd))
pines <- read.csv('~/Chapter_1-2/Pines.csv')
pinesheight_reg = lm(Hgt97~Hgt90, data = pines)
summary(pinesheight_reg)
anova(pinesheight_reg)
plot(pinesheight_reg)
with(pines, plot(Hgt90,Hgt97))
pines$sqrt90 <- with(pines, sqrt(Hgt90))
pines$sqrt97 <- with(pines, sqrt(Hgt97))
with(pines,plot(sqrt90,sqrt97))
confint(pinesheight_reg)
pinesheight_reg2 = lm(Hgt97~Hgt96, data = pines)
summary(pinesheight_reg2)
anova(pinesheight_reg2)
confint(pinesheight_reg2)

horsemdf <-data.frame(horsem)
horseprices<- read.csv('~/Chapter_1-2/HorsePrices.csv')      
horsepricevage = lm(Price~Age, data =horseprices)
horsepricevheight = lm(Price~Height, data)
horsem <- filter(horseprices, Sex == 'm')
horsem <- data.frame(horseprices, Sex == 'm')
my_data <- filter(horseprices.Sex == 'm')
horseprices[1:4, 1:50]
df1 <- data.frame(horseprices[1,2])
horsem <- horseprices[horseprices$Sex == "m" ,]
horsef<- horseprices[horseprices$Sex == "f",]
horsempricevage = lm(Price~Age, data = horsem)
horsempricevheight = lm(Price~Height, data = horsem)
summary(horsempricevage)
summary(horsempricevheight)
horsefpricevage = lm(Price~Age, data = horsef)
horsefpricevheight = lm(Price~Height, data = horsef)
summary(horsefpricevage)
summary(horsefpricevheight)
confint(horsefpricevage)
confint(horsempricevheight)